spring:
  flyway:
    enabled: true
    schemas: personal_finance_tracker
  jpa:
    database: default
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/pft?ApplicationName=pft-service'
    username: pft
    password: pft
    hikari:
      minimum-idle: 5
      maximum-pool-size: 25
      idle-timeout: 30000
